server:
  port: 50005
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      database: flights
      host: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
planes:
  service: PLANES
  path: /
