server:
  port: 50051

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    annotation:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}      
management:
  security:
    enabled: false
  health:
    defaults: true
    sensitive: true
  endpoints:
    web:
      expose: "*"
    health:
      show-details: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST

sendgrid:
  apikey: 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
  url: 7PQ75Wu0RRWOo9nkE2UMOA

mail:
  queue: send-mail-request
